### ISSUE TITLE
Max and Min Bounds incorrect

### ISSUE THREAD

**Issue by jnflint** [ptrv/go-gpx#4]
Looks like Max and Min are swapped in the following function

func (b *Bounds) String() string {
    return fmt.Sprintf("Max: %+v, %+v Min: %+v, %+v",
        b.MinLat, b.MinLon, b.MaxLat, b.MaxLon)

**Comment by ptrv** [comment]
Thanks for reporting. Fixed with c93804873f99672c0c8f6af17b7b51f316074dc5
